import React, {useEffect, useMemo, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Status='scheduled'|'action'|'waiting'|'applied'|'closed';
type Interview={id:string;company:string;role:string;person:string;status:Status;date:string;time?:string;next:string;hq?:[number,number];timezone?:string;};
const interviews:Interview[]=[
 {id:'bol',company:'BOL Agency',role:'Product Design Engineer',person:'Chief AI Officer interview',status:'scheduled',date:'2026-09-02',time:'10:00 AM',next:'Prepare for interview',hq:[52.37,4.9],timezone:'Amsterdam'},
 {id:'owner',company:'Owner.com',role:'Founding design team',person:'Portfolio review',status:'scheduled',date:'2026-09-04',time:'1:00 PM',next:'Review portfolio narrative',hq:[37.77,-122.42],timezone:'San Francisco'},
 {id:'amazon',company:'Amazon',role:'Principal UX Designer',person:'AWS hiring-manager interview',status:'scheduled',date:'2026-09-05',time:'11:30 AM',next:'Confirm interview prep',hq:[47.61,-122.33],timezone:'Seattle'},
 {id:'dialpad',company:'Dialpad',role:'Staff Product Designer',person:'Hiring-manager interview',status:'scheduled',date:'2026-09-08',time:'9:00 AM',next:'Send availability',hq:[37.39,-122.08],timezone:'Mountain View'},
 {id:'a1',company:'A1',role:'Product Designer',person:'New sourcing message',status:'action',date:'2026-08-25',next:'Reply to sourcing message',hq:undefined},
 {id:'disney',company:'Disney',role:'Sr UX Product Designer',person:'Team interview requested',status:'waiting',date:'2026-09-02',next:'Await scheduling details',hq:[34.05,-118.24],timezone:'Burbank'},
 {id:'tesla',company:'Tesla',role:'Staff Designer, UI Design',person:'Recruiter call held',status:'waiting',date:'2026-09-02',next:'Watch for outcome',hq:[37.39,-122.03],timezone:'Austin'},
 {id:'affirm',company:'Affirm',role:'Staff Product Designer',person:'Design-leader interview',status:'scheduled',date:'2026-09-10',next:'Build case-study set',hq:[37.77,-122.42],timezone:'San Francisco'},
];
const statusLabel:Record<Status,string>={scheduled:'Scheduled',action:'Needs action',waiting:'Waiting',applied:'Applied',closed:'Closed'};
function formatDate(v:string){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}
function Globe({item,replay}:{item:Interview;replay:number}){const canvas=useRef<HTMLCanvasElement>(null); const reduced=useRef(false); useEffect(()=>{reduced.current=matchMedia('(prefers-reduced-motion: reduce)').matches; const c=canvas.current;if(!c)return; const ctx=c.getContext('2d');if(!ctx)return; let raf=0;let start=performance.now(); const draw=(now:number)=>{const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=Math.round(w*d);c.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w,h)*.37;const pulse=reduced.current?1:Math.min(1,(now-start)/850);ctx.strokeStyle='rgba(132,180,193,.24)';ctx.lineWidth=1;for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(cx,cy,r,r*(.22+i*.13),0,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='rgba(180,212,213,.45)';ctx.stroke();const [lat,lon]=item.hq??[39.8,-98.6];const x=cx+(lon+98.6)/110*r*.75;const y=cy-(lat-39.8)/65*r*.85;ctx.beginPath();ctx.arc(x,y,8+10*pulse,0,Math.PI*2);ctx.fillStyle='rgba(219,116,83,.2)';ctx.fill();ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle='#db7453';ctx.fill();if(!reduced.current)raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[item,replay]);return <div className="globe-wrap"><canvas ref={canvas} aria-label={`${item.company} geographic footprint`} /><div className="globe-copy"><span>Selected company</span><h1>{item.company}</h1><p>{item.hq?<>HQ · {item.timezone}<br/><small>Footprint data verified for this view</small></>:<>HQ location not publicly verified<br/><small>Showing a neutral fallback</small></>}</p></div><div className="north">N</div></div>}
function App(){const [selected,setSelected]=useState(interviews[0]);const [query,setQuery]=useState('');const [replay,setReplay]=useState(0);const [filter,setFilter]=useState<Status|null>(null);const list=useMemo(()=>interviews.filter(x=>(!filter||x.status===filter)&&(`${x.company} ${x.role} ${x.person}`.toLowerCase().includes(query.toLowerCase()))),[query,filter]);useEffect(()=>{if(!list.some(x=>x.id===selected.id)&&list[0])setSelected(list[0])},[list,selected.id]);return <main className="shell"><section className="map"><header><span className="wordmark">SCOUT</span><span>UPDATED SEP 3, 2026</span></header><Globe item={selected} replay={replay}/><button className="replay" onClick={()=>setReplay(x=>x+1)}>Replay story <span>↻</span></button></section><aside className="rail"><div className="rail-head"><div><span className="eyebrow">NOW / NEXT</span><h2>Interview queue</h2></div><span className="count">{list.length} active</span></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search queue" aria-label="Search queue"/></label><div className="filters">{(['action','scheduled','waiting'] as Status[]).map(s=><button className={filter===s?'on':''} onClick={()=>setFilter(filter===s?null:s)} key={s}>{statusLabel[s]}</button>)}</div><div className="queue" role="listbox" aria-label="Interview queue" tabIndex={0}>{list.map(x=><button role="option" aria-selected={x.id===selected.id} className={'row '+(x.id===selected.id?'selected':'')} key={x.id} onClick={()=>setSelected(x)}><time>{formatDate(x.date)}{x.time&&<small>{x.time}</small>}</time><span className="row-main"><strong>{x.company}</strong><small>{x.person}</small><em>{x.next}</em></span><span className={'status '+x.status}>{statusLabel[x.status]}</span></button>)}</div>{!list.length&&<p className="empty">No queue items match. Clear a filter or search.</p>}<div className="scroll-cue">Scroll for more <span>↓</span></div></aside></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
